### PR TITLE
revert reconciliation on direct statefulset/deployment replica count change made by HPA or anything else

### LINKED ISSUE #160: HPA doesn't work with operator v0.0.5
Using an HPA with operator v0.0.5 doesn't work because the operator immediately tries to reconcile the deployment/statefulset back to the original replica count. Most likely due to PR https://github.com/druid-io/druid-operator/pull/115

The HPA works as expected with operator v0.0.4. 

Sample HPA spec from druid cluster.yaml: 
```
      hpAutoscaler:
        maxReplicas: 6
        minReplicas: 3
        scaleTargetRef:
           apiVersion: apps/v1
           kind: Deployment
           name: druid-cluster-brokers
        metrics:
         - type: Resource
           resource:
            name: cpu
            targetAverageUtilization: 50
```

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #160

### Description

Do not reconcile statefulset/deployment when replica count is updated by something outside of operator e.g. HPA.

<hr>

This PR has:
- [ ] been tested on a real K8S cluster to ensure creation of a brand new Druid cluster works.
- [ ] been tested for backward compatibility on a real K*S cluster by applying the changes introduced here on an existing Druid cluster. If there are any backward incompatible changes then they have been noted in the PR description.
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added documentation for new or modified features or behaviors.

<hr>

##### Key changed/added files in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

### CODE REVIEW

**Comment by AdheipSingh** [comment]
LGTM, i guess we can cut a release after this fix.

**Review by nishantmonu51 — APPROVED** [review]
👍 , LGTM.

File: controllers/druid/handler.go [hunk 1]
```diff
@@ -1120,11 +1120,12 @@ func makeStatefulSet(nodeSpec *v1alpha1.DruidNodeSpec, m *v1alpha1.Druid, ls map
...
-// currently only checks for replica count mismatch, can be extended further
 func statefulSetIsEquals(obj1, obj2 object) bool {
-	o1 := obj1.(*appsv1.StatefulSet)
-	o2 := obj2.(*appsv1.StatefulSet)
-	return *o1.Spec.Replicas == *o2.Spec.Replicas
+
+	// This used to match replica counts, but was reverted to fix https://github.com/druid-io/druid-operator/issues/160
+	// because it is legitimate for HPA to change replica counts and operator shouldn't reset those.
+
+	return true;
```
Comment (AdheipSingh) [inline controllers/druid/handler.go:1128]: ha semi-colons
